#!/bin/bash

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_71 ]
then
    cd $OPENSHIFT_DATA_DIR
    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u71-b15/jdk-8u71-linux-x64.tar.gz
    tar -zxf jdk-8u71-linux-x64.tar.gz
    export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_71/bin:$PATH
    export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk/jdk1.8.0_71"
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.10 ]
then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-2.10-bin.zip
    unzip gradle-2.10-bin.zip
    rm -f gradle-2.10-bin.zip
fi
