#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

PID=$(ps -ef | grep java.*\.jar | grep -v grep | awk '{ print $2 }')

if [ -z "$PID" ]
then
    client_result "Application is already stopped"
else
    kill $PID
fi

cd $OPENSHIFT_DATA_DIR/tomcat/webapps/
rm -rf ROOT/
rm -f ROOT.war